// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fastgateway-dev/backend-v2/internal/models"
	"github.com/fastgateway-dev/backend-v2/internal/services/clients"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientAttachmentService creates a new instance of MockClientAttachmentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientAttachmentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientAttachmentService {
	mock := &MockClientAttachmentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientAttachmentService is an autogenerated mock type for the ClientAttachmentServiceInterface type
type MockClientAttachmentService struct {
	mock.Mock
}

type MockClientAttachmentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientAttachmentService) EXPECT() *MockClientAttachmentService_Expecter {
	return &MockClientAttachmentService_Expecter{mock: &_m.Mock}
}

// ApproveStage provides a mock function for the type MockClientAttachmentService
func (_mock *MockClientAttachmentService) ApproveStage(approvalID uuid.UUID, stageID uuid.UUID, reviewer *models.User) (*models.Approval, error) {
	ret := _mock.Called(approvalID, stageID, reviewer)

	if len(ret) == 0 {
		panic("no return value specified for ApproveStage")
	}

	var r0 *models.Approval
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, *models.User) (*models.Approval, error)); ok {
		return returnFunc(approvalID, stageID, reviewer)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, *models.User) *models.Approval); ok {
		r0 = returnFunc(approvalID, stageID, reviewer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Approval)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID, *models.User) error); ok {
		r1 = returnFunc(approvalID, stageID, reviewer)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientAttachmentService_ApproveStage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveStage'
type MockClientAttachmentService_ApproveStage_Call struct {
	*mock.Call
}

// ApproveStage is a helper method to define mock.On call
//   - approvalID uuid.UUID
//   - stageID uuid.UUID
//   - reviewer *models.User
func (_e *MockClientAttachmentService_Expecter) ApproveStage(approvalID any, stageID any, reviewer any) *MockClientAttachmentService_ApproveStage_Call {
	return &MockClientAttachmentService_ApproveStage_Call{Call: _e.mock.On("ApproveStage", approvalID, stageID, reviewer)}
}

func (_c *MockClientAttachmentService_ApproveStage_Call) Run(run func(approvalID uuid.UUID, stageID uuid.UUID, reviewer *models.User)) *MockClientAttachmentService_ApproveStage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *models.User
		if args[2] != nil {
			arg2 = args[2].(*models.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientAttachmentService_ApproveStage_Call) Return(approval *models.Approval, err error) *MockClientAttachmentService_ApproveStage_Call {
	_c.Call.Return(approval, err)
	return _c
}

func (_c *MockClientAttachmentService_ApproveStage_Call) RunAndReturn(run func(approvalID uuid.UUID, stageID uuid.UUID, reviewer *models.User) (*models.Approval, error)) *MockClientAttachmentService_ApproveStage_Call {
	_c.Call.Return(run)
	return _c
}

// AttachFromClient provides a mock function for the type MockClientAttachmentService
func (_mock *MockClientAttachmentService) AttachFromClient(clientID uuid.UUID, input *clients.AttachFromClientInput, submittedBy uuid.UUID) (*models.ClientRouteAttachment, error) {
	ret := _mock.Called(clientID, input, submittedBy)

	if len(ret) == 0 {
		panic("no return value specified for AttachFromClient")
	}

	var r0 *models.ClientRouteAttachment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, *clients.AttachFromClientInput, uuid.UUID) (*models.ClientRouteAttachment, error)); ok {
		return returnFunc(clientID, input, submittedBy)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, *clients.AttachFromClientInput, uuid.UUID) *models.ClientRouteAttachment); ok {
		r0 = returnFunc(clientID, input, submittedBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ClientRouteAttachment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, *clients.AttachFromClientInput, uuid.UUID) error); ok {
		r1 = returnFunc(clientID, input, submittedBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientAttachmentService_AttachFromClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachFromClient'
type MockClientAttachmentService_AttachFromClient_Call struct {
	*mock.Call
}

// AttachFromClient is a helper method to define mock.On call
//   - clientID uuid.UUID
//   - input *clients.AttachFromClientInput
//   - submittedBy uuid.UUID
func (_e *MockClientAttachmentService_Expecter) AttachFromClient(clientID any, input any, submittedBy any) *MockClientAttachmentService_AttachFromClient_Call {
	return &MockClientAttachmentService_AttachFromClient_Call{Call: _e.mock.On("AttachFromClient", clientID, input, submittedBy)}
}

func (_c *MockClientAttachmentService_AttachFromClient_Call) Run(run func(clientID uuid.UUID, input *clients.AttachFromClientInput, submittedBy uuid.UUID)) *MockClientAttachmentService_AttachFromClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 *clients.AttachFromClientInput
		if args[1] != nil {
			arg1 = args[1].(*clients.AttachFromClientInput)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientAttachmentService_AttachFromClient_Call) Return(clientRouteAttachment *models.ClientRouteAttachment, err error) *MockClientAttachmentService_AttachFromClient_Call {
	_c.Call.Return(clientRouteAttachment, err)
	return _c
}

func (_c *MockClientAttachmentService_AttachFromClient_Call) RunAndReturn(run func(clientID uuid.UUID, input *clients.AttachFromClientInput, submittedBy uuid.UUID) (*models.ClientRouteAttachment, error)) *MockClientAttachmentService_AttachFromClient_Call {
	_c.Call.Return(run)
	return _c
}

// AttachFromRoute provides a mock function for the type MockClientAttachmentService
func (_mock *MockClientAttachmentService) AttachFromRoute(routeID uuid.UUID, input *clients.AttachFromRouteInput, submittedBy uuid.UUID) (*models.ClientRouteAttachment, error) {
	ret := _mock.Called(routeID, input, submittedBy)

	if len(ret) == 0 {
		panic("no return value specified for AttachFromRoute")
	}

	var r0 *models.ClientRouteAttachment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, *clients.AttachFromRouteInput, uuid.UUID) (*models.ClientRouteAttachment, error)); ok {
		return returnFunc(routeID, input, submittedBy)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, *clients.AttachFromRouteInput, uuid.UUID) *models.ClientRouteAttachment); ok {
		r0 = returnFunc(routeID, input, submittedBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ClientRouteAttachment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, *clients.AttachFromRouteInput, uuid.UUID) error); ok {
		r1 = returnFunc(routeID, input, submittedBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientAttachmentService_AttachFromRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachFromRoute'
type MockClientAttachmentService_AttachFromRoute_Call struct {
	*mock.Call
}

// AttachFromRoute is a helper method to define mock.On call
//   - routeID uuid.UUID
//   - input *clients.AttachFromRouteInput
//   - submittedBy uuid.UUID
func (_e *MockClientAttachmentService_Expecter) AttachFromRoute(routeID any, input any, submittedBy any) *MockClientAttachmentService_AttachFromRoute_Call {
	return &MockClientAttachmentService_AttachFromRoute_Call{Call: _e.mock.On("AttachFromRoute", routeID, input, submittedBy)}
}

func (_c *MockClientAttachmentService_AttachFromRoute_Call) Run(run func(routeID uuid.UUID, input *clients.AttachFromRouteInput, submittedBy uuid.UUID)) *MockClientAttachmentService_AttachFromRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 *clients.AttachFromRouteInput
		if args[1] != nil {
			arg1 = args[1].(*clients.AttachFromRouteInput)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientAttachmentService_AttachFromRoute_Call) Return(clientRouteAttachment *models.ClientRouteAttachment, err error) *MockClientAttachmentService_AttachFromRoute_Call {
	_c.Call.Return(clientRouteAttachment, err)
	return _c
}

func (_c *MockClientAttachmentService_AttachFromRoute_Call) RunAndReturn(run func(routeID uuid.UUID, input *clients.AttachFromRouteInput, submittedBy uuid.UUID) (*models.ClientRouteAttachment, error)) *MockClientAttachmentService_AttachFromRoute_Call {
	_c.Call.Return(run)
	return _c
}

// GetApproval provides a mock function for the type MockClientAttachmentService
func (_mock *MockClientAttachmentService) GetApproval(id uuid.UUID) (*models.Approval, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetApproval")
	}

	var r0 *models.Approval
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*models.Approval, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *models.Approval); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Approval)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientAttachmentService_GetApproval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApproval'
type MockClientAttachmentService_GetApproval_Call struct {
	*mock.Call
}

// GetApproval is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockClientAttachmentService_Expecter) GetApproval(id any) *MockClientAttachmentService_GetApproval_Call {
	return &MockClientAttachmentService_GetApproval_Call{Call: _e.mock.On("GetApproval", id)}
}

func (_c *MockClientAttachmentService_GetApproval_Call) Run(run func(id uuid.UUID)) *MockClientAttachmentService_GetApproval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientAttachmentService_GetApproval_Call) Return(approval *models.Approval, err error) *MockClientAttachmentService_GetApproval_Call {
	_c.Call.Return(approval, err)
	return _c
}

func (_c *MockClientAttachmentService_GetApproval_Call) RunAndReturn(run func(id uuid.UUID) (*models.Approval, error)) *MockClientAttachmentService_GetApproval_Call {
	_c.Call.Return(run)
	return _c
}

// ListApprovalsByProjectID provides a mock function for the type MockClientAttachmentService
func (_mock *MockClientAttachmentService) ListApprovalsByProjectID(projectID uuid.UUID, page int, limit int, status string) ([]models.Approval, int64, error) {
	ret := _mock.Called(projectID, page, limit, status)

	if len(ret) == 0 {
		panic("no return value specified for ListApprovalsByProjectID")
	}

	var r0 []models.Approval
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, int, int, string) ([]models.Approval, int64, error)); ok {
		return returnFunc(projectID, page, limit, status)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, int, int, string) []models.Approval); ok {
		r0 = returnFunc(projectID, page, limit, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Approval)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, int, int, string) int64); ok {
		r1 = returnFunc(projectID, page, limit, status)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(uuid.UUID, int, int, string) error); ok {
		r2 = returnFunc(projectID, page, limit, status)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockClientAttachmentService_ListApprovalsByProjectID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListApprovalsByProjectID'
type MockClientAttachmentService_ListApprovalsByProjectID_Call struct {
	*mock.Call
}

// ListApprovalsByProjectID is a helper method to define mock.On call
//   - projectID uuid.UUID
//   - page int
//   - limit int
//   - status string
func (_e *MockClientAttachmentService_Expecter) ListApprovalsByProjectID(projectID any, page any, limit any, status any) *MockClientAttachmentService_ListApprovalsByProjectID_Call {
	return &MockClientAttachmentService_ListApprovalsByProjectID_Call{Call: _e.mock.On("ListApprovalsByProjectID", projectID, page, limit, status)}
}

func (_c *MockClientAttachmentService_ListApprovalsByProjectID_Call) Run(run func(projectID uuid.UUID, page int, limit int, status string)) *MockClientAttachmentService_ListApprovalsByProjectID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClientAttachmentService_ListApprovalsByProjectID_Call) Return(approvals []models.Approval, n int64, err error) *MockClientAttachmentService_ListApprovalsByProjectID_Call {
	_c.Call.Return(approvals, n, err)
	return _c
}

func (_c *MockClientAttachmentService_ListApprovalsByProjectID_Call) RunAndReturn(run func(projectID uuid.UUID, page int, limit int, status string) ([]models.Approval, int64, error)) *MockClientAttachmentService_ListApprovalsByProjectID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByClientID provides a mock function for the type MockClientAttachmentService
func (_mock *MockClientAttachmentService) ListByClientID(clientID uuid.UUID) ([]models.ClientRouteAttachment, error) {
	ret := _mock.Called(clientID)

	if len(ret) == 0 {
		panic("no return value specified for ListByClientID")
	}

	var r0 []models.ClientRouteAttachment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) ([]models.ClientRouteAttachment, error)); ok {
		return returnFunc(clientID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) []models.ClientRouteAttachment); ok {
		r0 = returnFunc(clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ClientRouteAttachment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(clientID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientAttachmentService_ListByClientID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByClientID'
type MockClientAttachmentService_ListByClientID_Call struct {
	*mock.Call
}

// ListByClientID is a helper method to define mock.On call
//   - clientID uuid.UUID
func (_e *MockClientAttachmentService_Expecter) ListByClientID(clientID any) *MockClientAttachmentService_ListByClientID_Call {
	return &MockClientAttachmentService_ListByClientID_Call{Call: _e.mock.On("ListByClientID", clientID)}
}

func (_c *MockClientAttachmentService_ListByClientID_Call) Run(run func(clientID uuid.UUID)) *MockClientAttachmentService_ListByClientID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientAttachmentService_ListByClientID_Call) Return(clientRouteAttachments []models.ClientRouteAttachment, err error) *MockClientAttachmentService_ListByClientID_Call {
	_c.Call.Return(clientRouteAttachments, err)
	return _c
}

func (_c *MockClientAttachmentService_ListByClientID_Call) RunAndReturn(run func(clientID uuid.UUID) ([]models.ClientRouteAttachment, error)) *MockClientAttachmentService_ListByClientID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByRouteID provides a mock function for the type MockClientAttachmentService
func (_mock *MockClientAttachmentService) ListByRouteID(routeID uuid.UUID) ([]models.ClientRouteAttachment, error) {
	ret := _mock.Called(routeID)

	if len(ret) == 0 {
		panic("no return value specified for ListByRouteID")
	}

	var r0 []models.ClientRouteAttachment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) ([]models.ClientRouteAttachment, error)); ok {
		return returnFunc(routeID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) []models.ClientRouteAttachment); ok {
		r0 = returnFunc(routeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ClientRouteAttachment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(routeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientAttachmentService_ListByRouteID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByRouteID'
type MockClientAttachmentService_ListByRouteID_Call struct {
	*mock.Call
}

// ListByRouteID is a helper method to define mock.On call
//   - routeID uuid.UUID
func (_e *MockClientAttachmentService_Expecter) ListByRouteID(routeID any) *MockClientAttachmentService_ListByRouteID_Call {
	return &MockClientAttachmentService_ListByRouteID_Call{Call: _e.mock.On("ListByRouteID", routeID)}
}

func (_c *MockClientAttachmentService_ListByRouteID_Call) Run(run func(routeID uuid.UUID)) *MockClientAttachmentService_ListByRouteID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientAttachmentService_ListByRouteID_Call) Return(clientRouteAttachments []models.ClientRouteAttachment, err error) *MockClientAttachmentService_ListByRouteID_Call {
	_c.Call.Return(clientRouteAttachments, err)
	return _c
}

func (_c *MockClientAttachmentService_ListByRouteID_Call) RunAndReturn(run func(routeID uuid.UUID) ([]models.ClientRouteAttachment, error)) *MockClientAttachmentService_ListByRouteID_Call {
	_c.Call.Return(run)
	return _c
}

// RejectStage provides a mock function for the type MockClientAttachmentService
func (_mock *MockClientAttachmentService) RejectStage(approvalID uuid.UUID, stageID uuid.UUID, reviewer *models.User, comment string) (*models.Approval, error) {
	ret := _mock.Called(approvalID, stageID, reviewer, comment)

	if len(ret) == 0 {
		panic("no return value specified for RejectStage")
	}

	var r0 *models.Approval
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, *models.User, string) (*models.Approval, error)); ok {
		return returnFunc(approvalID, stageID, reviewer, comment)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, *models.User, string) *models.Approval); ok {
		r0 = returnFunc(approvalID, stageID, reviewer, comment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Approval)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID, *models.User, string) error); ok {
		r1 = returnFunc(approvalID, stageID, reviewer, comment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientAttachmentService_RejectStage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectStage'
type MockClientAttachmentService_RejectStage_Call struct {
	*mock.Call
}

// RejectStage is a helper method to define mock.On call
//   - approvalID uuid.UUID
//   - stageID uuid.UUID
//   - reviewer *models.User
//   - comment string
func (_e *MockClientAttachmentService_Expecter) RejectStage(approvalID any, stageID any, reviewer any, comment any) *MockClientAttachmentService_RejectStage_Call {
	return &MockClientAttachmentService_RejectStage_Call{Call: _e.mock.On("RejectStage", approvalID, stageID, reviewer, comment)}
}

func (_c *MockClientAttachmentService_RejectStage_Call) Run(run func(approvalID uuid.UUID, stageID uuid.UUID, reviewer *models.User, comment string)) *MockClientAttachmentService_RejectStage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *models.User
		if args[2] != nil {
			arg2 = args[2].(*models.User)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClientAttachmentService_RejectStage_Call) Return(approval *models.Approval, err error) *MockClientAttachmentService_RejectStage_Call {
	_c.Call.Return(approval, err)
	return _c
}

func (_c *MockClientAttachmentService_RejectStage_Call) RunAndReturn(run func(approvalID uuid.UUID, stageID uuid.UUID, reviewer *models.User, comment string) (*models.Approval, error)) *MockClientAttachmentService_RejectStage_Call {
	_c.Call.Return(run)
	return _c
}

// RequestDetach provides a mock function for the type MockClientAttachmentService
func (_mock *MockClientAttachmentService) RequestDetach(attachmentID uuid.UUID, submittedBy uuid.UUID) (*models.ClientRouteAttachment, error) {
	ret := _mock.Called(attachmentID, submittedBy)

	if len(ret) == 0 {
		panic("no return value specified for RequestDetach")
	}

	var r0 *models.ClientRouteAttachment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (*models.ClientRouteAttachment, error)); ok {
		return returnFunc(attachmentID, submittedBy)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) *models.ClientRouteAttachment); ok {
		r0 = returnFunc(attachmentID, submittedBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ClientRouteAttachment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(attachmentID, submittedBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientAttachmentService_RequestDetach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestDetach'
type MockClientAttachmentService_RequestDetach_Call struct {
	*mock.Call
}

// RequestDetach is a helper method to define mock.On call
//   - attachmentID uuid.UUID
//   - submittedBy uuid.UUID
func (_e *MockClientAttachmentService_Expecter) RequestDetach(attachmentID any, submittedBy any) *MockClientAttachmentService_RequestDetach_Call {
	return &MockClientAttachmentService_RequestDetach_Call{Call: _e.mock.On("RequestDetach", attachmentID, submittedBy)}
}

func (_c *MockClientAttachmentService_RequestDetach_Call) Run(run func(attachmentID uuid.UUID, submittedBy uuid.UUID)) *MockClientAttachmentService_RequestDetach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientAttachmentService_RequestDetach_Call) Return(clientRouteAttachment *models.ClientRouteAttachment, err error) *MockClientAttachmentService_RequestDetach_Call {
	_c.Call.Return(clientRouteAttachment, err)
	return _c
}

func (_c *MockClientAttachmentService_RequestDetach_Call) RunAndReturn(run func(attachmentID uuid.UUID, submittedBy uuid.UUID) (*models.ClientRouteAttachment, error)) *MockClientAttachmentService_RequestDetach_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientService creates a new instance of MockClientService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientService {
	mock := &MockClientService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientService is an autogenerated mock type for the ClientServiceInterface type
type MockClientService struct {
	mock.Mock
}

type MockClientService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientService) EXPECT() *MockClientService_Expecter {
	return &MockClientService_Expecter{mock: &_m.Mock}
}

// AddHeader provides a mock function for the type MockClientService
func (_mock *MockClientService) AddHeader(clientID uuid.UUID, input *clients.CreateClientHeaderInput, createdBy uuid.UUID) (*models.ClientHeader, error) {
	ret := _mock.Called(clientID, input, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for AddHeader")
	}

	var r0 *models.ClientHeader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, *clients.CreateClientHeaderInput, uuid.UUID) (*models.ClientHeader, error)); ok {
		return returnFunc(clientID, input, createdBy)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, *clients.CreateClientHeaderInput, uuid.UUID) *models.ClientHeader); ok {
		r0 = returnFunc(clientID, input, createdBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ClientHeader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, *clients.CreateClientHeaderInput, uuid.UUID) error); ok {
		r1 = returnFunc(clientID, input, createdBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientService_AddHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddHeader'
type MockClientService_AddHeader_Call struct {
	*mock.Call
}

// AddHeader is a helper method to define mock.On call
//   - clientID uuid.UUID
//   - input *clients.CreateClientHeaderInput
//   - createdBy uuid.UUID
func (_e *MockClientService_Expecter) AddHeader(clientID any, input any, createdBy any) *MockClientService_AddHeader_Call {
	return &MockClientService_AddHeader_Call{Call: _e.mock.On("AddHeader", clientID, input, createdBy)}
}

func (_c *MockClientService_AddHeader_Call) Run(run func(clientID uuid.UUID, input *clients.CreateClientHeaderInput, createdBy uuid.UUID)) *MockClientService_AddHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 *clients.CreateClientHeaderInput
		if args[1] != nil {
			arg1 = args[1].(*clients.CreateClientHeaderInput)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientService_AddHeader_Call) Return(clientHeader *models.ClientHeader, err error) *MockClientService_AddHeader_Call {
	_c.Call.Return(clientHeader, err)
	return _c
}

func (_c *MockClientService_AddHeader_Call) RunAndReturn(run func(clientID uuid.UUID, input *clients.CreateClientHeaderInput, createdBy uuid.UUID) (*models.ClientHeader, error)) *MockClientService_AddHeader_Call {
	_c.Call.Return(run)
	return _c
}

// AddIP provides a mock function for the type MockClientService
func (_mock *MockClientService) AddIP(clientID uuid.UUID, input *clients.CreateClientIPInput, createdBy uuid.UUID) (*models.ClientIPAddress, error) {
	ret := _mock.Called(clientID, input, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for AddIP")
	}

	var r0 *models.ClientIPAddress
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, *clients.CreateClientIPInput, uuid.UUID) (*models.ClientIPAddress, error)); ok {
		return returnFunc(clientID, input, createdBy)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, *clients.CreateClientIPInput, uuid.UUID) *models.ClientIPAddress); ok {
		r0 = returnFunc(clientID, input, createdBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ClientIPAddress)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, *clients.CreateClientIPInput, uuid.UUID) error); ok {
		r1 = returnFunc(clientID, input, createdBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientService_AddIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddIP'
type MockClientService_AddIP_Call struct {
	*mock.Call
}

// AddIP is a helper method to define mock.On call
//   - clientID uuid.UUID
//   - input *clients.CreateClientIPInput
//   - createdBy uuid.UUID
func (_e *MockClientService_Expecter) AddIP(clientID any, input any, createdBy any) *MockClientService_AddIP_Call {
	return &MockClientService_AddIP_Call{Call: _e.mock.On("AddIP", clientID, input, createdBy)}
}

func (_c *MockClientService_AddIP_Call) Run(run func(clientID uuid.UUID, input *clients.CreateClientIPInput, createdBy uuid.UUID)) *MockClientService_AddIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 *clients.CreateClientIPInput
		if args[1] != nil {
			arg1 = args[1].(*clients.CreateClientIPInput)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientService_AddIP_Call) Return(clientIPAddress *models.ClientIPAddress, err error) *MockClientService_AddIP_Call {
	_c.Call.Return(clientIPAddress, err)
	return _c
}

func (_c *MockClientService_AddIP_Call) RunAndReturn(run func(clientID uuid.UUID, input *clients.CreateClientIPInput, createdBy uuid.UUID) (*models.ClientIPAddress, error)) *MockClientService_AddIP_Call {
	_c.Call.Return(run)
	return _c
}

// ConfigureJWT provides a mock function for the type MockClientService
func (_mock *MockClientService) ConfigureJWT(ctx context.Context, clientID uuid.UUID, input *clients.ConfigureJWTInput, createdBy uuid.UUID) (*clients.ConfigureJWTResponse, error) {
	ret := _mock.Called(ctx, clientID, input, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for ConfigureJWT")
	}

	var r0 *clients.ConfigureJWTResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *clients.ConfigureJWTInput, uuid.UUID) (*clients.ConfigureJWTResponse, error)); ok {
		return returnFunc(ctx, clientID, input, createdBy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *clients.ConfigureJWTInput, uuid.UUID) *clients.ConfigureJWTResponse); ok {
		r0 = returnFunc(ctx, clientID, input, createdBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clients.ConfigureJWTResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *clients.ConfigureJWTInput, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, clientID, input, createdBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientService_ConfigureJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigureJWT'
type MockClientService_ConfigureJWT_Call struct {
	*mock.Call
}

// ConfigureJWT is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
//   - input *clients.ConfigureJWTInput
//   - createdBy uuid.UUID
func (_e *MockClientService_Expecter) ConfigureJWT(ctx any, clientID any, input any, createdBy any) *MockClientService_ConfigureJWT_Call {
	return &MockClientService_ConfigureJWT_Call{Call: _e.mock.On("ConfigureJWT", ctx, clientID, input, createdBy)}
}

func (_c *MockClientService_ConfigureJWT_Call) Run(run func(ctx context.Context, clientID uuid.UUID, input *clients.ConfigureJWTInput, createdBy uuid.UUID)) *MockClientService_ConfigureJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *clients.ConfigureJWTInput
		if args[2] != nil {
			arg2 = args[2].(*clients.ConfigureJWTInput)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClientService_ConfigureJWT_Call) Return(configureJWTResponse *clients.ConfigureJWTResponse, err error) *MockClientService_ConfigureJWT_Call {
	_c.Call.Return(configureJWTResponse, err)
	return _c
}

func (_c *MockClientService_ConfigureJWT_Call) RunAndReturn(run func(ctx context.Context, clientID uuid.UUID, input *clients.ConfigureJWTInput, createdBy uuid.UUID) (*clients.ConfigureJWTResponse, error)) *MockClientService_ConfigureJWT_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockClientService
func (_mock *MockClientService) Create(input *clients.CreateClientInput, createdBy uuid.UUID) (*models.Client, error) {
	ret := _mock.Called(input, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*clients.CreateClientInput, uuid.UUID) (*models.Client, error)); ok {
		return returnFunc(input, createdBy)
	}
	if returnFunc, ok := ret.Get(0).(func(*clients.CreateClientInput, uuid.UUID) *models.Client); ok {
		r0 = returnFunc(input, createdBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*clients.CreateClientInput, uuid.UUID) error); ok {
		r1 = returnFunc(input, createdBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockClientService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - input *clients.CreateClientInput
//   - createdBy uuid.UUID
func (_e *MockClientService_Expecter) Create(input any, createdBy any) *MockClientService_Create_Call {
	return &MockClientService_Create_Call{Call: _e.mock.On("Create", input, createdBy)}
}

func (_c *MockClientService_Create_Call) Run(run func(input *clients.CreateClientInput, createdBy uuid.UUID)) *MockClientService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *clients.CreateClientInput
		if args[0] != nil {
			arg0 = args[0].(*clients.CreateClientInput)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientService_Create_Call) Return(client *models.Client, err error) *MockClientService_Create_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockClientService_Create_Call) RunAndReturn(run func(input *clients.CreateClientInput, createdBy uuid.UUID) (*models.Client, error)) *MockClientService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockClientService
func (_mock *MockClientService) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockClientService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockClientService_Expecter) Delete(ctx any, id any) *MockClientService_Delete_Call {
	return &MockClientService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockClientService_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockClientService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientService_Delete_Call) Return(err error) *MockClientService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientService_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockClientService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateAPIKey provides a mock function for the type MockClientService
func (_mock *MockClientService) GenerateAPIKey(ctx context.Context, clientID uuid.UUID, input *clients.GenerateAPIKeyInput, createdBy uuid.UUID) (*clients.GenerateAPIKeyResponse, error) {
	ret := _mock.Called(ctx, clientID, input, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAPIKey")
	}

	var r0 *clients.GenerateAPIKeyResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *clients.GenerateAPIKeyInput, uuid.UUID) (*clients.GenerateAPIKeyResponse, error)); ok {
		return returnFunc(ctx, clientID, input, createdBy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *clients.GenerateAPIKeyInput, uuid.UUID) *clients.GenerateAPIKeyResponse); ok {
		r0 = returnFunc(ctx, clientID, input, createdBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clients.GenerateAPIKeyResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *clients.GenerateAPIKeyInput, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, clientID, input, createdBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientService_GenerateAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAPIKey'
type MockClientService_GenerateAPIKey_Call struct {
	*mock.Call
}

// GenerateAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
//   - input *clients.GenerateAPIKeyInput
//   - createdBy uuid.UUID
func (_e *MockClientService_Expecter) GenerateAPIKey(ctx any, clientID any, input any, createdBy any) *MockClientService_GenerateAPIKey_Call {
	return &MockClientService_GenerateAPIKey_Call{Call: _e.mock.On("GenerateAPIKey", ctx, clientID, input, createdBy)}
}

func (_c *MockClientService_GenerateAPIKey_Call) Run(run func(ctx context.Context, clientID uuid.UUID, input *clients.GenerateAPIKeyInput, createdBy uuid.UUID)) *MockClientService_GenerateAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *clients.GenerateAPIKeyInput
		if args[2] != nil {
			arg2 = args[2].(*clients.GenerateAPIKeyInput)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClientService_GenerateAPIKey_Call) Return(generateAPIKeyResponse *clients.GenerateAPIKeyResponse, err error) *MockClientService_GenerateAPIKey_Call {
	_c.Call.Return(generateAPIKeyResponse, err)
	return _c
}

func (_c *MockClientService_GenerateAPIKey_Call) RunAndReturn(run func(ctx context.Context, clientID uuid.UUID, input *clients.GenerateAPIKeyInput, createdBy uuid.UUID) (*clients.GenerateAPIKeyResponse, error)) *MockClientService_GenerateAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockClientService
func (_mock *MockClientService) GetByID(id uuid.UUID) (*models.Client, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*models.Client, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *models.Client); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockClientService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockClientService_Expecter) GetByID(id any) *MockClientService_GetByID_Call {
	return &MockClientService_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockClientService_GetByID_Call) Run(run func(id uuid.UUID)) *MockClientService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientService_GetByID_Call) Return(client *models.Client, err error) *MockClientService_GetByID_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockClientService_GetByID_Call) RunAndReturn(run func(id uuid.UUID) (*models.Client, error)) *MockClientService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockClientService
func (_mock *MockClientService) List(page int, limit int, teamID *uuid.UUID) ([]models.Client, int64, error) {
	ret := _mock.Called(page, limit, teamID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Client
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(int, int, *uuid.UUID) ([]models.Client, int64, error)); ok {
		return returnFunc(page, limit, teamID)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int, *uuid.UUID) []models.Client); ok {
		r0 = returnFunc(page, limit, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int, *uuid.UUID) int64); ok {
		r1 = returnFunc(page, limit, teamID)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(int, int, *uuid.UUID) error); ok {
		r2 = returnFunc(page, limit, teamID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockClientService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockClientService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - page int
//   - limit int
//   - teamID *uuid.UUID
func (_e *MockClientService_Expecter) List(page any, limit any, teamID any) *MockClientService_List_Call {
	return &MockClientService_List_Call{Call: _e.mock.On("List", page, limit, teamID)}
}

func (_c *MockClientService_List_Call) Run(run func(page int, limit int, teamID *uuid.UUID)) *MockClientService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientService_List_Call) Return(clients1 []models.Client, n int64, err error) *MockClientService_List_Call {
	_c.Call.Return(clients1, n, err)
	return _c
}

func (_c *MockClientService_List_Call) RunAndReturn(run func(page int, limit int, teamID *uuid.UUID) ([]models.Client, int64, error)) *MockClientService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListHeaders provides a mock function for the type MockClientService
func (_mock *MockClientService) ListHeaders(clientID uuid.UUID) ([]models.ClientHeader, error) {
	ret := _mock.Called(clientID)

	if len(ret) == 0 {
		panic("no return value specified for ListHeaders")
	}

	var r0 []models.ClientHeader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) ([]models.ClientHeader, error)); ok {
		return returnFunc(clientID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) []models.ClientHeader); ok {
		r0 = returnFunc(clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ClientHeader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(clientID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientService_ListHeaders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHeaders'
type MockClientService_ListHeaders_Call struct {
	*mock.Call
}

// ListHeaders is a helper method to define mock.On call
//   - clientID uuid.UUID
func (_e *MockClientService_Expecter) ListHeaders(clientID any) *MockClientService_ListHeaders_Call {
	return &MockClientService_ListHeaders_Call{Call: _e.mock.On("ListHeaders", clientID)}
}

func (_c *MockClientService_ListHeaders_Call) Run(run func(clientID uuid.UUID)) *MockClientService_ListHeaders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientService_ListHeaders_Call) Return(clientHeaders []models.ClientHeader, err error) *MockClientService_ListHeaders_Call {
	_c.Call.Return(clientHeaders, err)
	return _c
}

func (_c *MockClientService_ListHeaders_Call) RunAndReturn(run func(clientID uuid.UUID) ([]models.ClientHeader, error)) *MockClientService_ListHeaders_Call {
	_c.Call.Return(run)
	return _c
}

// ListIPs provides a mock function for the type MockClientService
func (_mock *MockClientService) ListIPs(clientID uuid.UUID) ([]models.ClientIPAddress, error) {
	ret := _mock.Called(clientID)

	if len(ret) == 0 {
		panic("no return value specified for ListIPs")
	}

	var r0 []models.ClientIPAddress
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) ([]models.ClientIPAddress, error)); ok {
		return returnFunc(clientID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) []models.ClientIPAddress); ok {
		r0 = returnFunc(clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ClientIPAddress)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(clientID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientService_ListIPs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIPs'
type MockClientService_ListIPs_Call struct {
	*mock.Call
}

// ListIPs is a helper method to define mock.On call
//   - clientID uuid.UUID
func (_e *MockClientService_Expecter) ListIPs(clientID any) *MockClientService_ListIPs_Call {
	return &MockClientService_ListIPs_Call{Call: _e.mock.On("ListIPs", clientID)}
}

func (_c *MockClientService_ListIPs_Call) Run(run func(clientID uuid.UUID)) *MockClientService_ListIPs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientService_ListIPs_Call) Return(clientIPAddresss []models.ClientIPAddress, err error) *MockClientService_ListIPs_Call {
	_c.Call.Return(clientIPAddresss, err)
	return _c
}

func (_c *MockClientService_ListIPs_Call) RunAndReturn(run func(clientID uuid.UUID) ([]models.ClientIPAddress, error)) *MockClientService_ListIPs_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveHeader provides a mock function for the type MockClientService
func (_mock *MockClientService) RemoveHeader(clientID uuid.UUID, headerID uuid.UUID) error {
	ret := _mock.Called(clientID, headerID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(clientID, headerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientService_RemoveHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveHeader'
type MockClientService_RemoveHeader_Call struct {
	*mock.Call
}

// RemoveHeader is a helper method to define mock.On call
//   - clientID uuid.UUID
//   - headerID uuid.UUID
func (_e *MockClientService_Expecter) RemoveHeader(clientID any, headerID any) *MockClientService_RemoveHeader_Call {
	return &MockClientService_RemoveHeader_Call{Call: _e.mock.On("RemoveHeader", clientID, headerID)}
}

func (_c *MockClientService_RemoveHeader_Call) Run(run func(clientID uuid.UUID, headerID uuid.UUID)) *MockClientService_RemoveHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientService_RemoveHeader_Call) Return(err error) *MockClientService_RemoveHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientService_RemoveHeader_Call) RunAndReturn(run func(clientID uuid.UUID, headerID uuid.UUID) error) *MockClientService_RemoveHeader_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveIP provides a mock function for the type MockClientService
func (_mock *MockClientService) RemoveIP(clientID uuid.UUID, ipID uuid.UUID) error {
	ret := _mock.Called(clientID, ipID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveIP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(clientID, ipID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientService_RemoveIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveIP'
type MockClientService_RemoveIP_Call struct {
	*mock.Call
}

// RemoveIP is a helper method to define mock.On call
//   - clientID uuid.UUID
//   - ipID uuid.UUID
func (_e *MockClientService_Expecter) RemoveIP(clientID any, ipID any) *MockClientService_RemoveIP_Call {
	return &MockClientService_RemoveIP_Call{Call: _e.mock.On("RemoveIP", clientID, ipID)}
}

func (_c *MockClientService_RemoveIP_Call) Run(run func(clientID uuid.UUID, ipID uuid.UUID)) *MockClientService_RemoveIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientService_RemoveIP_Call) Return(err error) *MockClientService_RemoveIP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientService_RemoveIP_Call) RunAndReturn(run func(clientID uuid.UUID, ipID uuid.UUID) error) *MockClientService_RemoveIP_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveJWT provides a mock function for the type MockClientService
func (_mock *MockClientService) RemoveJWT(ctx context.Context, clientID uuid.UUID) error {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveJWT")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientService_RemoveJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveJWT'
type MockClientService_RemoveJWT_Call struct {
	*mock.Call
}

// RemoveJWT is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
func (_e *MockClientService_Expecter) RemoveJWT(ctx any, clientID any) *MockClientService_RemoveJWT_Call {
	return &MockClientService_RemoveJWT_Call{Call: _e.mock.On("RemoveJWT", ctx, clientID)}
}

func (_c *MockClientService_RemoveJWT_Call) Run(run func(ctx context.Context, clientID uuid.UUID)) *MockClientService_RemoveJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientService_RemoveJWT_Call) Return(err error) *MockClientService_RemoveJWT_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientService_RemoveJWT_Call) RunAndReturn(run func(ctx context.Context, clientID uuid.UUID) error) *MockClientService_RemoveJWT_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAPIKey provides a mock function for the type MockClientService
func (_mock *MockClientService) RevokeAPIKey(ctx context.Context, clientID uuid.UUID) error {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAPIKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientService_RevokeAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAPIKey'
type MockClientService_RevokeAPIKey_Call struct {
	*mock.Call
}

// RevokeAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
func (_e *MockClientService_Expecter) RevokeAPIKey(ctx any, clientID any) *MockClientService_RevokeAPIKey_Call {
	return &MockClientService_RevokeAPIKey_Call{Call: _e.mock.On("RevokeAPIKey", ctx, clientID)}
}

func (_c *MockClientService_RevokeAPIKey_Call) Run(run func(ctx context.Context, clientID uuid.UUID)) *MockClientService_RevokeAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientService_RevokeAPIKey_Call) Return(err error) *MockClientService_RevokeAPIKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientService_RevokeAPIKey_Call) RunAndReturn(run func(ctx context.Context, clientID uuid.UUID) error) *MockClientService_RevokeAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// SetAllowedMethods provides a mock function for the type MockClientService
func (_mock *MockClientService) SetAllowedMethods(clientID uuid.UUID, methods []string) (*models.Client, error) {
	ret := _mock.Called(clientID, methods)

	if len(ret) == 0 {
		panic("no return value specified for SetAllowedMethods")
	}

	var r0 *models.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, []string) (*models.Client, error)); ok {
		return returnFunc(clientID, methods)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, []string) *models.Client); ok {
		r0 = returnFunc(clientID, methods)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, []string) error); ok {
		r1 = returnFunc(clientID, methods)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientService_SetAllowedMethods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAllowedMethods'
type MockClientService_SetAllowedMethods_Call struct {
	*mock.Call
}

// SetAllowedMethods is a helper method to define mock.On call
//   - clientID uuid.UUID
//   - methods []string
func (_e *MockClientService_Expecter) SetAllowedMethods(clientID any, methods any) *MockClientService_SetAllowedMethods_Call {
	return &MockClientService_SetAllowedMethods_Call{Call: _e.mock.On("SetAllowedMethods", clientID, methods)}
}

func (_c *MockClientService_SetAllowedMethods_Call) Run(run func(clientID uuid.UUID, methods []string)) *MockClientService_SetAllowedMethods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientService_SetAllowedMethods_Call) Return(client *models.Client, err error) *MockClientService_SetAllowedMethods_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockClientService_SetAllowedMethods_Call) RunAndReturn(run func(clientID uuid.UUID, methods []string) (*models.Client, error)) *MockClientService_SetAllowedMethods_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockClientService
func (_mock *MockClientService) Update(id uuid.UUID, input *clients.UpdateClientInput) (*models.Client, error) {
	ret := _mock.Called(id, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, *clients.UpdateClientInput) (*models.Client, error)); ok {
		return returnFunc(id, input)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, *clients.UpdateClientInput) *models.Client); ok {
		r0 = returnFunc(id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, *clients.UpdateClientInput) error); ok {
		r1 = returnFunc(id, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockClientService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id uuid.UUID
//   - input *clients.UpdateClientInput
func (_e *MockClientService_Expecter) Update(id any, input any) *MockClientService_Update_Call {
	return &MockClientService_Update_Call{Call: _e.mock.On("Update", id, input)}
}

func (_c *MockClientService_Update_Call) Run(run func(id uuid.UUID, input *clients.UpdateClientInput)) *MockClientService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 *clients.UpdateClientInput
		if args[1] != nil {
			arg1 = args[1].(*clients.UpdateClientInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientService_Update_Call) Return(client *models.Client, err error) *MockClientService_Update_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockClientService_Update_Call) RunAndReturn(run func(id uuid.UUID, input *clients.UpdateClientInput) (*models.Client, error)) *MockClientService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateClientMTLS provides a mock function for the type MockClientService
func (_mock *MockClientService) UpdateClientMTLS(ctx context.Context, clientID uuid.UUID, input *clients.UpdateClientMTLSInput, updatedBy uuid.UUID) (*models.Client, error) {
	ret := _mock.Called(ctx, clientID, input, updatedBy)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClientMTLS")
	}

	var r0 *models.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *clients.UpdateClientMTLSInput, uuid.UUID) (*models.Client, error)); ok {
		return returnFunc(ctx, clientID, input, updatedBy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *clients.UpdateClientMTLSInput, uuid.UUID) *models.Client); ok {
		r0 = returnFunc(ctx, clientID, input, updatedBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *clients.UpdateClientMTLSInput, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, clientID, input, updatedBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientService_UpdateClientMTLS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateClientMTLS'
type MockClientService_UpdateClientMTLS_Call struct {
	*mock.Call
}

// UpdateClientMTLS is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
//   - input *clients.UpdateClientMTLSInput
//   - updatedBy uuid.UUID
func (_e *MockClientService_Expecter) UpdateClientMTLS(ctx any, clientID any, input any, updatedBy any) *MockClientService_UpdateClientMTLS_Call {
	return &MockClientService_UpdateClientMTLS_Call{Call: _e.mock.On("UpdateClientMTLS", ctx, clientID, input, updatedBy)}
}

func (_c *MockClientService_UpdateClientMTLS_Call) Run(run func(ctx context.Context, clientID uuid.UUID, input *clients.UpdateClientMTLSInput, updatedBy uuid.UUID)) *MockClientService_UpdateClientMTLS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *clients.UpdateClientMTLSInput
		if args[2] != nil {
			arg2 = args[2].(*clients.UpdateClientMTLSInput)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClientService_UpdateClientMTLS_Call) Return(client *models.Client, err error) *MockClientService_UpdateClientMTLS_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockClientService_UpdateClientMTLS_Call) RunAndReturn(run func(ctx context.Context, clientID uuid.UUID, input *clients.UpdateClientMTLSInput, updatedBy uuid.UUID) (*models.Client, error)) *MockClientService_UpdateClientMTLS_Call {
	_c.Call.Return(run)
	return _c
}
