version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  enable:
    - gofmt
