package routeplan

import (
	"flag"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
	"sigs.k8s.io/yaml"
)

// updateGolden rewrites every golden file this package asserts against.
//
//	go test ./internal/routeplan/ -run TestGolden -update-golden
//
// Regenerating is a deliberate act: the diff it produces IS the review. Never
// run it to "make the build green" -- a changed golden means either a bug was
// introduced or a behaviour change was intended, and the commit message must
// say which.
//
// Scope note: this flag belongs to package routeplan only. The 72 route
// goldens under internal/services/testdata/golden/ are regenerated by that
// package's own identically-named flag; the two never run together.
var updateGolden = flag.Bool("update-golden", false, "rewrite golden files instead of asserting against them")

// assertGolden marshals obj to YAML and compares it against
// testdata/golden/<name>.yaml.
func assertGolden(t *testing.T, name string, obj any) {
	t.Helper()

	got, err := yaml.Marshal(obj)
	require.NoError(t, err, "marshalling %s", name)

	path := filepath.Join("testdata", "golden", name+".yaml")

	if *updateGolden {
		require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
		require.NoError(t, os.WriteFile(path, got, 0o644))
		return
	}

	want, err := os.ReadFile(path)
	require.NoErrorf(t, err,
		"golden file %s is missing; regenerate with:\n"+
			"  go test ./internal/routeplan/ -run TestGolden -update-golden", path)

	require.Equalf(t, string(want), string(got),
		"golden mismatch for %s\n"+
			"If this change is INTENDED, regenerate with -update-golden and explain it in the commit message.", path)
}
