// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.4
// source: podinfo_header.proto

package header

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HeaderService_Header_FullMethodName = "/header.HeaderService/Header"
)

// HeaderServiceClient is the client API for HeaderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HeaderServiceClient interface {
	Header(ctx context.Context, in *HeaderRequest, opts ...grpc.CallOption) (*HeaderResponse, error)
}

type headerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHeaderServiceClient(cc grpc.ClientConnInterface) HeaderServiceClient {
	return &headerServiceClient{cc}
}

func (c *headerServiceClient) Header(ctx context.Context, in *HeaderRequest, opts ...grpc.CallOption) (*HeaderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeaderResponse)
	err := c.cc.Invoke(ctx, HeaderService_Header_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HeaderServiceServer is the server API for HeaderService service.
// All implementations must embed UnimplementedHeaderServiceServer
// for forward compatibility.
type HeaderServiceServer interface {
	Header(context.Context, *HeaderRequest) (*HeaderResponse, error)
	mustEmbedUnimplementedHeaderServiceServer()
}

// UnimplementedHeaderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHeaderServiceServer struct{}

func (UnimplementedHeaderServiceServer) Header(context.Context, *HeaderRequest) (*HeaderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Header not implemented")
}
func (UnimplementedHeaderServiceServer) mustEmbedUnimplementedHeaderServiceServer() {}
func (UnimplementedHeaderServiceServer) testEmbeddedByValue()                       {}

// UnsafeHeaderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HeaderServiceServer will
// result in compilation errors.
type UnsafeHeaderServiceServer interface {
	mustEmbedUnimplementedHeaderServiceServer()
}

func RegisterHeaderServiceServer(s grpc.ServiceRegistrar, srv HeaderServiceServer) {
	// If the following call panics, it indicates UnimplementedHeaderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HeaderService_ServiceDesc, srv)
}

func _HeaderService_Header_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeaderServiceServer).Header(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HeaderService_Header_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeaderServiceServer).Header(ctx, req.(*HeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HeaderService_ServiceDesc is the grpc.ServiceDesc for HeaderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HeaderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "header.HeaderService",
	HandlerType: (*HeaderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Header",
			Handler:    _HeaderService_Header_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "podinfo_header.proto",
}
