// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: podinfo_header.proto

package header

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeaderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderRequest) Reset() {
	*x = HeaderRequest{}
	mi := &file_podinfo_header_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderRequest) ProtoMessage() {}

func (x *HeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podinfo_header_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderRequest.ProtoReflect.Descriptor instead.
func (*HeaderRequest) Descriptor() ([]byte, []int) {
	return file_podinfo_header_proto_rawDescGZIP(), []int{0}
}

type HeaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       []string               `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderResponse) Reset() {
	*x = HeaderResponse{}
	mi := &file_podinfo_header_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderResponse) ProtoMessage() {}

func (x *HeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podinfo_header_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderResponse.ProtoReflect.Descriptor instead.
func (*HeaderResponse) Descriptor() ([]byte, []int) {
	return file_podinfo_header_proto_rawDescGZIP(), []int{1}
}

func (x *HeaderResponse) GetHeaders() []string {
	if x != nil {
		return x.Headers
	}
	return nil
}

var File_podinfo_header_proto protoreflect.FileDescriptor

const file_podinfo_header_proto_rawDesc = "" +
	"\n" +
	"\x14podinfo_header.proto\x12\x06header\"\x0f\n" +
	"\rheaderRequest\"*\n" +
	"\x0eheaderResponse\x12\x18\n" +
	"\aheaders\x18\x01 \x03(\tR\aheaders2J\n" +
	"\rHeaderService\x129\n" +
	"\x06Header\x12\x15.header.headerRequest\x1a\x16.header.headerResponse\"\x00B\n" +
	"Z\b./headerb\x06proto3"

var (
	file_podinfo_header_proto_rawDescOnce sync.Once
	file_podinfo_header_proto_rawDescData []byte
)

func file_podinfo_header_proto_rawDescGZIP() []byte {
	file_podinfo_header_proto_rawDescOnce.Do(func() {
		file_podinfo_header_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_podinfo_header_proto_rawDesc), len(file_podinfo_header_proto_rawDesc)))
	})
	return file_podinfo_header_proto_rawDescData
}

var file_podinfo_header_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_podinfo_header_proto_goTypes = []any{
	(*HeaderRequest)(nil),  // 0: header.headerRequest
	(*HeaderResponse)(nil), // 1: header.headerResponse
}
var file_podinfo_header_proto_depIdxs = []int32{
	0, // 0: header.HeaderService.Header:input_type -> header.headerRequest
	1, // 1: header.HeaderService.Header:output_type -> header.headerResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_podinfo_header_proto_init() }
func file_podinfo_header_proto_init() {
	if File_podinfo_header_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_podinfo_header_proto_rawDesc), len(file_podinfo_header_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_podinfo_header_proto_goTypes,
		DependencyIndexes: file_podinfo_header_proto_depIdxs,
		MessageInfos:      file_podinfo_header_proto_msgTypes,
	}.Build()
	File_podinfo_header_proto = out.File
	file_podinfo_header_proto_goTypes = nil
	file_podinfo_header_proto_depIdxs = nil
}
