// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: podinfo_info.proto

package info

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_podinfo_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podinfo_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_podinfo_info_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Revision      string                 `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Logo          string                 `protobuf:"bytes,5,opt,name=logo,proto3" json:"logo,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Goos          string                 `protobuf:"bytes,7,opt,name=goos,proto3" json:"goos,omitempty"`
	Goarch        string                 `protobuf:"bytes,8,opt,name=goarch,proto3" json:"goarch,omitempty"`
	Runtime       string                 `protobuf:"bytes,9,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Numgoroutine  string                 `protobuf:"bytes,10,opt,name=numgoroutine,proto3" json:"numgoroutine,omitempty"`
	Numcpu        string                 `protobuf:"bytes,11,opt,name=numcpu,proto3" json:"numcpu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_podinfo_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podinfo_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_podinfo_info_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *InfoResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *InfoResponse) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *InfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InfoResponse) GetGoos() string {
	if x != nil {
		return x.Goos
	}
	return ""
}

func (x *InfoResponse) GetGoarch() string {
	if x != nil {
		return x.Goarch
	}
	return ""
}

func (x *InfoResponse) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *InfoResponse) GetNumgoroutine() string {
	if x != nil {
		return x.Numgoroutine
	}
	return ""
}

func (x *InfoResponse) GetNumcpu() string {
	if x != nil {
		return x.Numcpu
	}
	return ""
}

var File_podinfo_info_proto protoreflect.FileDescriptor

const file_podinfo_info_proto_rawDesc = "" +
	"\n" +
	"\x12podinfo_info.proto\x12\x04info\"\r\n" +
	"\vInfoRequest\"\xa6\x02\n" +
	"\fInfoResponse\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\tR\brevision\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12\x12\n" +
	"\x04logo\x18\x05 \x01(\tR\x04logo\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12\x12\n" +
	"\x04goos\x18\a \x01(\tR\x04goos\x12\x16\n" +
	"\x06goarch\x18\b \x01(\tR\x06goarch\x12\x18\n" +
	"\aruntime\x18\t \x01(\tR\aruntime\x12\"\n" +
	"\fnumgoroutine\x18\n" +
	" \x01(\tR\fnumgoroutine\x12\x16\n" +
	"\x06numcpu\x18\v \x01(\tR\x06numcpu2>\n" +
	"\vInfoService\x12/\n" +
	"\x04Info\x12\x11.info.InfoRequest\x1a\x12.info.InfoResponse\"\x00B\bZ\x06./infob\x06proto3"

var (
	file_podinfo_info_proto_rawDescOnce sync.Once
	file_podinfo_info_proto_rawDescData []byte
)

func file_podinfo_info_proto_rawDescGZIP() []byte {
	file_podinfo_info_proto_rawDescOnce.Do(func() {
		file_podinfo_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_podinfo_info_proto_rawDesc), len(file_podinfo_info_proto_rawDesc)))
	})
	return file_podinfo_info_proto_rawDescData
}

var file_podinfo_info_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_podinfo_info_proto_goTypes = []any{
	(*InfoRequest)(nil),  // 0: info.InfoRequest
	(*InfoResponse)(nil), // 1: info.InfoResponse
}
var file_podinfo_info_proto_depIdxs = []int32{
	0, // 0: info.InfoService.Info:input_type -> info.InfoRequest
	1, // 1: info.InfoService.Info:output_type -> info.InfoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_podinfo_info_proto_init() }
func file_podinfo_info_proto_init() {
	if File_podinfo_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_podinfo_info_proto_rawDesc), len(file_podinfo_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_podinfo_info_proto_goTypes,
		DependencyIndexes: file_podinfo_info_proto_depIdxs,
		MessageInfos:      file_podinfo_info_proto_msgTypes,
	}.Build()
	File_podinfo_info_proto = out.File
	file_podinfo_info_proto_goTypes = nil
	file_podinfo_info_proto_depIdxs = nil
}
