package ai

import (
	"encoding/json"

	"github.com/fastgateway-dev/backend-v2/internal/models"
)

// GenerateMode represents the type of AI generation request
type GenerateMode string

const (
	ModeNaturalLanguage GenerateMode = "natural_language"
	ModeManifestImport  GenerateMode = "manifest_import"
)

// GenerateRequest represents a request to generate routes
type GenerateRequest struct {
	Mode       GenerateMode   `json:"mode"`
	Input      string         `json:"input"`
	Domain     *DomainContext `json:"domain,omitempty"`
	FormatHint string         `json:"formatHint,omitempty"`
}

// DomainContext provides context about the target domain
type DomainContext struct {
	ID         string   `json:"id"`
	Name       string   `json:"name"`
	Hostname   string   `json:"hostname"`
	Namespaces []string `json:"namespaces,omitempty"`
}

// ChunkType represents the type of streaming chunk
type ChunkType string

const (
	ChunkTypeContent ChunkType = "content"
	ChunkTypeRoute   ChunkType = "route"
	ChunkTypeWarning ChunkType = "warning"
	ChunkTypeError   ChunkType = "error"
	ChunkTypeDone    ChunkType = "done"
)

// StreamChunk represents a single chunk in the SSE stream
type StreamChunk struct {
	Type    ChunkType       `json:"type"`
	Content string          `json:"content,omitempty"`
	Route   *GeneratedRoute `json:"route,omitempty"`
	Warning *Warning        `json:"warning,omitempty"`
	Error   string          `json:"error,omitempty"`
	Index   int             `json:"index,omitempty"`
	Total   int             `json:"total,omitempty"`
}

// GeneratedRoute represents a route generated by AI
type GeneratedRoute struct {
	Name         string             `json:"name"`
	Description  string             `json:"description,omitempty"`
	Protocol     string             `json:"protocol,omitempty"` // "http" or "grpc"
	SecurityMode string             `json:"securityMode,omitempty"`
	Config       models.RouteConfig `json:"config"`
	Warnings     []Warning          `json:"warnings,omitempty"`
}

// Warning represents a warning about the generated route
type Warning struct {
	Field    string `json:"field,omitempty"`
	Category string `json:"category"` // unsupported_feature, partial_mapping, etc.
	Message  string `json:"message"`
	Severity string `json:"severity"` // "info" or "warning"
}

// AIStatus represents the status of the AI service
type AIStatus struct {
	Enabled  bool   `json:"enabled"`
	Provider string `json:"provider,omitempty"`
}

// ReviewRequest represents a request to review YAML changes
type ReviewRequest struct {
	Action       string   `json:"action"` // "create", "update", "delete"
	Description  string   `json:"description,omitempty"`
	ProposedYaml *YamlSet `json:"proposedYaml,omitempty"`
	CurrentYaml  *YamlSet `json:"currentYaml,omitempty"`
}

// YamlSet contains YAML strings for different resource types
type YamlSet struct {
	HttpRoute            string `json:"httpRoute,omitempty"`
	SecurityPolicy       string `json:"securityPolicy,omitempty"`
	BackendTrafficPolicy string `json:"backendTrafficPolicy,omitempty"`
	EnvoyExtensionPolicy string `json:"envoyExtensionPolicy,omitempty"`
	Backend              string `json:"backend,omitempty"`
}

// ReviewResult is the structured AI review response
type ReviewResult struct {
	Summary          string       `json:"summary"`
	Risks            []ReviewNote `json:"risks,omitempty"`
	SecurityNotes    []ReviewNote `json:"securityNotes,omitempty"`
	Suggestions      []string     `json:"suggestions,omitempty"`
	ConfigHighlights []string     `json:"configHighlights,omitempty"`
}

// ReviewNote is a risk or security note with severity
type ReviewNote struct {
	Severity string `json:"severity"` // "warning" or "info"
	Message  string `json:"message"`
}

// ChatMessage represents a single message in a chat conversation
type ChatMessage struct {
	Role    string `json:"role"` // "user" or "assistant"
	Content string `json:"content"`
}

// ChatContext provides context about what the user is currently configuring
type ChatContext struct {
	Type   string          `json:"type"` // "route" or "domain"
	Route  json.RawMessage `json:"route,omitempty"`
	Domain json.RawMessage `json:"domain,omitempty"`
}

// ChatRequest represents a chat request
type ChatRequest struct {
	Message string        `json:"message"`
	Context *ChatContext  `json:"context,omitempty"`
	History []ChatMessage `json:"history,omitempty"`
}
