// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: podinfo_env.proto

package env

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvRequest) Reset() {
	*x = EnvRequest{}
	mi := &file_podinfo_env_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvRequest) ProtoMessage() {}

func (x *EnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podinfo_env_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvRequest.ProtoReflect.Descriptor instead.
func (*EnvRequest) Descriptor() ([]byte, []int) {
	return file_podinfo_env_proto_rawDescGZIP(), []int{0}
}

type EnvResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvVars       []string               `protobuf:"bytes,1,rep,name=envVars,proto3" json:"envVars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvResponse) Reset() {
	*x = EnvResponse{}
	mi := &file_podinfo_env_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvResponse) ProtoMessage() {}

func (x *EnvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podinfo_env_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvResponse.ProtoReflect.Descriptor instead.
func (*EnvResponse) Descriptor() ([]byte, []int) {
	return file_podinfo_env_proto_rawDescGZIP(), []int{1}
}

func (x *EnvResponse) GetEnvVars() []string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

var File_podinfo_env_proto protoreflect.FileDescriptor

const file_podinfo_env_proto_rawDesc = "" +
	"\n" +
	"\x11podinfo_env.proto\x12\x03env\"\f\n" +
	"\n" +
	"EnvRequest\"'\n" +
	"\vEnvResponse\x12\x18\n" +
	"\aenvVars\x18\x01 \x03(\tR\aenvVars28\n" +
	"\n" +
	"EnvService\x12*\n" +
	"\x03Env\x12\x0f.env.EnvRequest\x1a\x10.env.EnvResponse\"\x00B\aZ\x05./envb\x06proto3"

var (
	file_podinfo_env_proto_rawDescOnce sync.Once
	file_podinfo_env_proto_rawDescData []byte
)

func file_podinfo_env_proto_rawDescGZIP() []byte {
	file_podinfo_env_proto_rawDescOnce.Do(func() {
		file_podinfo_env_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_podinfo_env_proto_rawDesc), len(file_podinfo_env_proto_rawDesc)))
	})
	return file_podinfo_env_proto_rawDescData
}

var file_podinfo_env_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_podinfo_env_proto_goTypes = []any{
	(*EnvRequest)(nil),  // 0: env.EnvRequest
	(*EnvResponse)(nil), // 1: env.EnvResponse
}
var file_podinfo_env_proto_depIdxs = []int32{
	0, // 0: env.EnvService.Env:input_type -> env.EnvRequest
	1, // 1: env.EnvService.Env:output_type -> env.EnvResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_podinfo_env_proto_init() }
func file_podinfo_env_proto_init() {
	if File_podinfo_env_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_podinfo_env_proto_rawDesc), len(file_podinfo_env_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_podinfo_env_proto_goTypes,
		DependencyIndexes: file_podinfo_env_proto_depIdxs,
		MessageInfos:      file_podinfo_env_proto_msgTypes,
	}.Build()
	File_podinfo_env_proto = out.File
	file_podinfo_env_proto_goTypes = nil
	file_podinfo_env_proto_depIdxs = nil
}
