// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: podinfo_delay.proto

package delay

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DelayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       int64                  `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelayRequest) Reset() {
	*x = DelayRequest{}
	mi := &file_podinfo_delay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelayRequest) ProtoMessage() {}

func (x *DelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podinfo_delay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelayRequest.ProtoReflect.Descriptor instead.
func (*DelayRequest) Descriptor() ([]byte, []int) {
	return file_podinfo_delay_proto_rawDescGZIP(), []int{0}
}

func (x *DelayRequest) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

type DelayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       int64                  `protobuf:"varint,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelayResponse) Reset() {
	*x = DelayResponse{}
	mi := &file_podinfo_delay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelayResponse) ProtoMessage() {}

func (x *DelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podinfo_delay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelayResponse.ProtoReflect.Descriptor instead.
func (*DelayResponse) Descriptor() ([]byte, []int) {
	return file_podinfo_delay_proto_rawDescGZIP(), []int{1}
}

func (x *DelayResponse) GetMessage() int64 {
	if x != nil {
		return x.Message
	}
	return 0
}

var File_podinfo_delay_proto protoreflect.FileDescriptor

const file_podinfo_delay_proto_rawDesc = "" +
	"\n" +
	"\x13podinfo_delay.proto\x12\x05delay\"(\n" +
	"\fDelayRequest\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x03R\aseconds\")\n" +
	"\rDelayResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\x03R\amessage2D\n" +
	"\fDelayService\x124\n" +
	"\x05Delay\x12\x13.delay.DelayRequest\x1a\x14.delay.DelayResponse\"\x00B\tZ\a./delayb\x06proto3"

var (
	file_podinfo_delay_proto_rawDescOnce sync.Once
	file_podinfo_delay_proto_rawDescData []byte
)

func file_podinfo_delay_proto_rawDescGZIP() []byte {
	file_podinfo_delay_proto_rawDescOnce.Do(func() {
		file_podinfo_delay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_podinfo_delay_proto_rawDesc), len(file_podinfo_delay_proto_rawDesc)))
	})
	return file_podinfo_delay_proto_rawDescData
}

var file_podinfo_delay_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_podinfo_delay_proto_goTypes = []any{
	(*DelayRequest)(nil),  // 0: delay.DelayRequest
	(*DelayResponse)(nil), // 1: delay.DelayResponse
}
var file_podinfo_delay_proto_depIdxs = []int32{
	0, // 0: delay.DelayService.Delay:input_type -> delay.DelayRequest
	1, // 1: delay.DelayService.Delay:output_type -> delay.DelayResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_podinfo_delay_proto_init() }
func file_podinfo_delay_proto_init() {
	if File_podinfo_delay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_podinfo_delay_proto_rawDesc), len(file_podinfo_delay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_podinfo_delay_proto_goTypes,
		DependencyIndexes: file_podinfo_delay_proto_depIdxs,
		MessageInfos:      file_podinfo_delay_proto_msgTypes,
	}.Build()
	File_podinfo_delay_proto = out.File
	file_podinfo_delay_proto_goTypes = nil
	file_podinfo_delay_proto_depIdxs = nil
}
