// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: podinfo_token.proto

package token

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_podinfo_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podinfo_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_podinfo_token_proto_rawDescGZIP(), []int{0}
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_podinfo_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podinfo_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_podinfo_token_proto_rawDescGZIP(), []int{1}
}

func (x *TokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *TokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_podinfo_token_proto protoreflect.FileDescriptor

const file_podinfo_token_proto_rawDesc = "" +
	"\n" +
	"\x13podinfo_token.proto\x12\x05token\"\x0e\n" +
	"\fTokenRequest\"]\n" +
	"\rTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1c\n" +
	"\texpiresAt\x18\x02 \x01(\tR\texpiresAt\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\x8a\x01\n" +
	"\fTokenService\x12<\n" +
	"\rTokenGenerate\x12\x13.token.TokenRequest\x1a\x14.token.TokenResponse\"\x00\x12<\n" +
	"\rTokenValidate\x12\x13.token.TokenRequest\x1a\x14.token.TokenResponse\"\x00B\tZ\a./tokenb\x06proto3"

var (
	file_podinfo_token_proto_rawDescOnce sync.Once
	file_podinfo_token_proto_rawDescData []byte
)

func file_podinfo_token_proto_rawDescGZIP() []byte {
	file_podinfo_token_proto_rawDescOnce.Do(func() {
		file_podinfo_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_podinfo_token_proto_rawDesc), len(file_podinfo_token_proto_rawDesc)))
	})
	return file_podinfo_token_proto_rawDescData
}

var file_podinfo_token_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_podinfo_token_proto_goTypes = []any{
	(*TokenRequest)(nil),  // 0: token.TokenRequest
	(*TokenResponse)(nil), // 1: token.TokenResponse
}
var file_podinfo_token_proto_depIdxs = []int32{
	0, // 0: token.TokenService.TokenGenerate:input_type -> token.TokenRequest
	0, // 1: token.TokenService.TokenValidate:input_type -> token.TokenRequest
	1, // 2: token.TokenService.TokenGenerate:output_type -> token.TokenResponse
	1, // 3: token.TokenService.TokenValidate:output_type -> token.TokenResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_podinfo_token_proto_init() }
func file_podinfo_token_proto_init() {
	if File_podinfo_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_podinfo_token_proto_rawDesc), len(file_podinfo_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_podinfo_token_proto_goTypes,
		DependencyIndexes: file_podinfo_token_proto_depIdxs,
		MessageInfos:      file_podinfo_token_proto_msgTypes,
	}.Build()
	File_podinfo_token_proto = out.File
	file_podinfo_token_proto_goTypes = nil
	file_podinfo_token_proto_depIdxs = nil
}
